spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/cash
    username: postgres
    password: qwerty
    pool-size: 30